version: "3.3"
services:
  web:
    build:
      context: ./config/web
    image: minutes-nginx
    ports:
      - 443:4443
      - 80:8080
    volumes:
      - .:/app
    depends_on:
      - app
  app:
    build: ./config/back
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      CACHE_ROUTES: 'false'
      DB.DRIVER: 'pgsql'
      DB.HOST: 'db'
      DB.PORT: 5432
      DB.SCHEMA: minutes
      DB.USER: root
      DB.PASSWORD: secret
      JWT.SIGNING_KEY: supersecret
  front:
    image: node:8-alpine
    entrypoint:
      - npm
      - run
      - build-dev
    volumes:
      - .:/app
    depends_on:
      - app
    working_dir: /app
  db:
    image: postgres:9-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: minutes
volumes:
  db:
