version: "3.3"
services:
  web:
    image: nginx:1.13-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  app:
    image: php:7.1-fpm-alpine
    volumes:
     - .:/app
